// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5M3vCJJLD2C8an2EJ1lsZ2FXAEaa2vt4',
    appId: '1:773952414668:web:36fa05a6b2b6b22016b369',
    messagingSenderId: '773952414668',
    projectId: 'mesajlar-a48b6',
    authDomain: 'mesajlar-a48b6.firebaseapp.com',
    databaseURL: 'https://mesajlar-a48b6-default-rtdb.firebaseio.com',
    storageBucket: 'mesajlar-a48b6.firebasestorage.app',
    measurementId: 'G-WKM1PVE3R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_dqJqV2ANw7Fo7egQayvIu8B02QPkJM',
    appId: '1:773952414668:android:6368d054e22f3ffb16b369',
    messagingSenderId: '773952414668',
    projectId: 'mesajlar-a48b6',
    databaseURL: 'https://mesajlar-a48b6-default-rtdb.firebaseio.com',
    storageBucket: 'mesajlar-a48b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCifyZSj-TS56j6x0bXH_V_MFzNX7FSZlo',
    appId: '1:773952414668:ios:d7889ffc6bafa31216b369',
    messagingSenderId: '773952414668',
    projectId: 'mesajlar-a48b6',
    databaseURL: 'https://mesajlar-a48b6-default-rtdb.firebaseio.com',
    storageBucket: 'mesajlar-a48b6.firebasestorage.app',
    iosBundleId: 'com.example.ottapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCifyZSj-TS56j6x0bXH_V_MFzNX7FSZlo',
    appId: '1:773952414668:ios:d7889ffc6bafa31216b369',
    messagingSenderId: '773952414668',
    projectId: 'mesajlar-a48b6',
    databaseURL: 'https://mesajlar-a48b6-default-rtdb.firebaseio.com',
    storageBucket: 'mesajlar-a48b6.firebasestorage.app',
    iosBundleId: 'com.example.ottapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5M3vCJJLD2C8an2EJ1lsZ2FXAEaa2vt4',
    appId: '1:773952414668:web:36fa05a6b2b6b22016b369',
    messagingSenderId: '773952414668',
    projectId: 'mesajlar-a48b6',
    authDomain: 'mesajlar-a48b6.firebaseapp.com',
    databaseURL: 'https://mesajlar-a48b6-default-rtdb.firebaseio.com',
    storageBucket: 'mesajlar-a48b6.firebasestorage.app',
    measurementId: 'G-WKM1PVE3R0',
  );
}
